// mobile/rust-core/src/ui/meetings_map.rs
// Map View Logic: Rendering Meeting Markers & Mini-Map Generation.
// Features: Positive Tags Only, Organizer + Count Label, System Navigation Integration.
// Architecture: Offline-first, decoupled from specific map engine.
// Year: 2026 | Rust Edition: 2024

use crate::db::schema::{Meeting, MeetingStatus, User};
use crate::dict::cts_parser::{CtsTag, TagStatus};
use chrono::{DateTime, Local};
use std::sync::Arc;
use tokio::sync::RwLock;
use log::{info, debug, warn};

/// Data structure for the main map markers (List/Map View).
#[derive(Clone, Debug)]
pub struct MapMarkerData {
    pub id: String,
    pub latitude: f64,
    pub longitude: f64,
    pub main_goal_label: String,      // e.g., "Kino • Kawa"
    pub organizer_label: String,      // e.g., "Anna + 4"
    pub time_label: String,           // e.g., "18:00"
    pub marker_color: String,         // "#000000" or "#888888"
}

/// Data structure for the Static Mini-Map in Meeting Details.
/// Contains bounds to fit both user and meeting location.
#[derive(Clone, Debug)]
pub struct MiniMapData {
    pub center_lat: f64,
    pub center_lon: f64,
    pub zoom_level: u8,               // Calculated to fit both points
    pub user_lat: f64,
    pub user_lon: f64,
    pub meeting_lat: f64,
    pub meeting_lon: f64,
    // In a real implementation, this might be a pre-rendered image URL or binary blob
    // generated by a native renderer or a headless browser.
    pub static_image_url: Option<String>, 
}

/// Generates markers for the main map view.
pub async fn generate_map_markers(
    db_manager: Arc<RwLock<crate::db::manager::DbManager>>,
    current_timestamp: u64,
    max_distance_km: f64,
    user_lat: f64,
    user_lon: f64,
) -> Result<Vec<MapMarkerData>, &'static str> {
    let db = db_manager.read().await;
    let database = db.database();

    // Fetch active meetings. 
    // Note: Filtering by distance should ideally happen in DB query for performance,
    // but we filter here for demonstration if DB doesn't support geo-queries directly yet.
    let meetings = database
        .meetings()
        .filter(|m| m.status.eq(MeetingStatus::Active))
        .collect()
        .await
        .map_err(|_| "ERR_DB_FETCH_FAILED")?;

    let mut markers = Vec::new();

    for meeting in meetings {
        // 1. Distance Check
        let dist = haversine_distance(user_lat, user_lon, meeting.latitude, meeting.longitude);
        if dist > max_distance_km {
            continue;
        }

        // 2. Parse Tags & Filter for POSITIVE ONLY
        let cts_tags = crate::dict::cts_parser::parse_cts(&meeting.tags_cts)
            .unwrap_or_default();

        let positive_tags: Vec<&CtsTag> = cts_tags
            .iter()
            .filter(|t| t.status == TagStatus::Positive)
            .collect();

        let main_goal_label = positive_tags
            .iter()
            .map(|t| t.word.clone())
            .collect::<Vec<String>>()
            .join(" • ");

        if main_goal_label.is_empty() {
            continue; 
        }

        // 3. Organizer + Count Label
        let participant_count = database
            .meeting_participants()
            .filter(|p| p.meeting_id.eq(&meeting.id))
            .count()
            .await
            .unwrap_or(0);
        
        let organizer_name = database
            .users()
            .filter(|u| u.id.eq(&meeting.organizer_id))
            .select(|u| u.display_name.clone())
            .into_first()
            .await
            .unwrap_or_else(|| "Anon".to_string());

        let organizer_label = format!("{} + {}", organizer_name, participant_count);

        // 4. Time Label
        let start_time_dt = DateTime::from_timestamp(meeting.start_time as i64, 0)
            .unwrap_or_default()
            .with_timezone(&Local);
        let time_label = start_time_dt.format("%H:%M").to_string();

        // 5. Color
        let marker_color = if meeting.start_time as u64 >= current_timestamp {
            "#000000".to_string()
        } else {
            "#888888".to_string()
        };

        markers.push(MapMarkerData {
            id: meeting.id,
            latitude: meeting.latitude,
            longitude: meeting.longitude,
            main_goal_label,
            organizer_label,
            time_label,
            marker_color,
        });
    }

    Ok(markers)
}

/// Generates data for the Static Mini-Map in the Details View.
/// Calculates center and zoom to fit both User Location and Meeting Location.
pub async fn generate_mini_map_data(
    db_manager: Arc<RwLock<crate::db::manager::DbManager>>,
    meeting_id: &str,
    user_lat: f64,
    user_lon: f64,
) -> Result<MiniMapData, &'static str> {
    let db = db_manager.read().await;
    let database = db.database();

    let meeting = database
        .meetings()
        .filter(|m| m.id.eq(meeting_id))
        .into_first()
        .await
        .ok_or("ERR_MEETING_NOT_FOUND")?;

    let m_lat = meeting.latitude;
    let m_lon = meeting.longitude;

    // Calculate bounding box
    let min_lat = user_lat.min(m_lat);
    let max_lat = user_lat.max(m_lat);
    let min_lon = user_lon.min(m_lon);
    let max_lon = user_lon.max(m_lon);

    // Center point
    let center_lat = (min_lat + max_lat) / 2.0;
    let center_lon = (min_lon + max_lon) / 2.0;

    // Simple Zoom Calculation (Logic depends on map provider, here is a heuristic)
    // Distance between points determines zoom.
    let dist = haversine_distance(user_lat, user_lon, m_lat, m_lon);
    
    // Heuristic: closer points = higher zoom (larger number), far points = lower zoom.
    // Assuming Zoom 15 is street level (~1km view), Zoom 10 is city level.
    let zoom_level = if dist < 0.1 {
        16 // Very close, show street
    } else if dist < 1.0 {
        15
    } else if dist < 5.0 {
        13
    } else if dist < 20.0 {
        11
    } else {
        9 // Far away, show region
    };

    Ok(MiniMapData {
        center_lat,
        center_lon,
        zoom_level,
        user_lat,
        user_lon,
        meeting_lat: m_lat,
        meeting_lon: m_lon,
        static_image_url: None, // To be populated by native renderer or tile fetcher
    })
}

/// Handles click on a marker in the main map.
/// Returns full details to trigger the Details View.
pub fn handle_marker_clicked(meeting_id: String) {
    info!("MSG_MAP_MARKER_CLICKED: {}", meeting_id);
    // Callback to UI: ui_controller.show_details(meeting_id)
}

/// Generates a URI to open the system's native map application.
/// Supports Android (geo:), iOS (maps:), and Desktop (https).
pub fn open_system_navigation(lat: f64, lon: f64, query_name: Option<&str>) -> String {
    let q = query_name.unwrap_or("Spotka Meeting");
    let encoded_q = urlencoding::encode(q);
    
    // Universal approach: Try geo URI first, fallback to HTTPS
    // Android handles geo:lat,lon?q=lat,lon(label)
    // iOS handles maps:lat,lon?q=lat,lon(label)
    
    // Using HTTPS to Google Maps / OSM is often most reliable across platforms if specific schemes fail
    // For pure native apps, we usually pass coordinates to FFI which calls Intent/URLSession
    
    // Return a generic Geo URI string that the FFI layer can parse and route correctly
    format!("geo:{},{},q({})", lat, lon, encoded_q)
}

/// Helper: Haversine distance (km)
fn haversine_distance(lat1: f64, lon1: f64, lat2: f64, lon2: f64) -> f64 {
    const R: f64 = 6371.0; // Earth radius in km
    let d_lat = (lat2 - lat1).to_radians();
    let d_lon = (lon2 - lon1).to_radians();
    let a = (d_lat / 2.0).sin().powi(2)
        + lat1.to_radians().cos() * lat2.to_radians().cos() * (d_lon / 2.0).sin().powi(2);
    let c = 2.0 * a.sqrt().atan2((1.0 - a).sqrt());
    R * c
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_zoom_calculation_logic() {
        // Simulate distances
        assert!(haversine_distance(52.0, 21.0, 52.001, 21.001) < 0.2); // ~150m
        assert!(haversine_distance(52.0, 21.0, 53.0, 22.0) > 100.0);   // ~130km
    }

    #[test]
    fn test_geo_uri_generation() {
        let uri = open_system_navigation(52.2297, 21.0122, Some("Warsaw Meetup"));
        assert!(uri.starts_with("geo:"));
        assert!(uri.contains("q("));
    }
}
